Traceback (most recent call last):
  File "/Users/stephenjerome/Desktop/SteveHorsesPro/steve_horses_pro.py", line 281, in <module>
    print(build_html(d))
  File "/Users/stephenjerome/Desktop/SteveHorsesPro/steve_horses_pro.py", line 168, in build_html
    meets = meets_for_day(day)
  File "/Users/stephenjerome/Desktop/SteveHorsesPro/steve_horses_pro.py", line 96, in meets_for_day
    js=_req("/v1/north-america/meets",{"start_date":d,"end_date":d})
  File "/Users/stephenjerome/Desktop/SteveHorsesPro/steve_horses_pro.py", line 46, in _req
    with urlopen(req, timeout=25, context=CTX) as r:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
