Traceback (most recent call last):
  File "/Users/stephenjerome/Desktop/SteveHorsesPro/steve_horses_pro.py", line 253, in <module>
    build()
  File "/Users/stephenjerome/Desktop/SteveHorsesPro/steve_horses_pro.py", line 169, in build
    meets = meets_today()
  File "/Users/stephenjerome/Desktop/SteveHorsesPro/steve_horses_pro.py", line 61, in meets_today
    js = _get("/v1/north-america/meets", {"start_date":DAY,"end_date":DAY}, tag="na_meets")
  File "/Users/stephenjerome/Desktop/SteveHorsesPro/steve_horses_pro.py", line 54, in _get
    txt = _fetch(url)
  File "/Users/stephenjerome/Desktop/SteveHorsesPro/steve_horses_pro.py", line 45, in _fetch
    with urlopen(req, timeout=30, context=CTX) as r:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
